### ISSUE TITLE
Model.json() vs jsonify

### ISSUE THREAD

**Issue by jhoover4** [bauerji/flask_pydantic#5]
Hello,

Thanks for the app! We were beginning to play around with it and wondering if the returned json could be wrapped in `jsonify` or if there is an advantage to not to. We have our `jsonify` set just right to play nice with Mongo, etc., so we wanted to make sure we didn't lose any of its advantages.

Thanks!

**Comment by bauerji** [comment]
Hi,

Could you please specify little bit more in a detail what you are trying to achieve? I am not sure if you are asking whether it is in general better to use pydantic's `Model` class and its `json()` method over classical `jsonify()` function with object to be serialized as its argument. Or if you just want to call `jsonify()` with already serialized object by `model.json()`.

Jirka

**Comment by jhoover4** [comment]
I guess I'm asking what the difference between the model `json` vs. `jsonify` and if, since we're using Flask, the return here should be wrapped in `jsonify`. Or do you think thats necessary? I don't know enough about Pydantic to be sure.

Thanks for responding!

**Comment by bauerji** [comment]
Well, in that case I advise you to learn more about [pydantic library](https://pydantic-docs.helpmanual.io/usage/models/) since it's really awesome. Using its models helps you to assure the types (schema) of your objects to serialize. You can define default values etc. whereas `jsonify` just takes what you give to it and converts it into serialized json string. I don't think however it would be wise to wrap models together with `jsonify` (like this `jsonify(model.json())`) because `model.json()` already returns string representation of the model so there is nothing left to be jsonified anymore.

Hope it helps

**Comment by jhoover4** [comment]
Ah I was more talking about the benefits of `jsonify` as outlined here: https://flask.palletsprojects.com/en/1.1.x/api/#flask.json.jsonify

I looked at the source code though and it seems like you're wrapping it in `Response` and adding the mimetype anyway so I think I'm all good!

**Comment by bauerji** [comment]
I am glad it worked out well! It is the point of this library to seamlessly convert your response model to json response 🙂
